name: "Micro Crystal AG RV-8803 Driver CI"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  driver:
    uses: catie-aq/zephyr_workflows/.github/workflows/driver.yml@main
    secrets:
      personal_access_token: ${{ secrets.PAT }}
    with:
      path: "samples"
